apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kubernetes-secret-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springk8s
  template:
    metadata:
      labels:
        app: springk8s
    spec:
      containers:
      - name: appcontainer
        image: spring-kubernetes-env
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: KUBERNETES_SECRETS_VALUE
          valueFrom:
            secretKeyRef:
              name: kuberntes-secrets
              key: platform
