apiVersion: v1
kind: Service
metadata:
  name: spring-kubernetes-secret-service
spec:
  type: LoadBalancer
  selector:
    app: springk8s
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
